name: flutter_clean_calendar
description: Simple and clean flutter calendar with ability to slide up/down to show weekly/monthly calendar.
version: 1.1.0
homepage: "https://github.com/pmcarlos/flutter_clean_calendar"

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
